### ISSUE TITLE
「讨论」增补关于全局认识的切入点

### ISSUE THREAD

**Issue by zapp926** [MaiYunfei2000/IA003CoCoSci#1]
对「计算认知科学」的全局认识或者其它学科，这四个问题是不能回避的，解答的方法可以使用时间、空间、变量三范式，突出权重意识的方法可以重点关注有趣度。

* 这个学科产生、设立之初要解决的根本问题是什么，因什么而生。

* 这个学科的核心话语体系。即这个学科最抽象、级别最高的概念模型有哪些。

* 二级三级演绎体系有什么。相当于核心话语体系的旁枝，阐述一些具体问题的概念。

* 「其它学科」是如何看待这个学科的。

**Comment by xdpwjj** [comment]
# 目标

当你问我**计算认知科学研究的是什么**，我能给你一个比较全局的答案。

# 目录

1. [信息搜索方向](#信息搜索方向)
    * [大牛](#大牛)
    * [实验室](#实验室)
    * [国际会议](#国际会议)
    * [关键文献](#关键文献)
    * [线索检索词](#线索检索词)
2. [执行策略](#执行策略)
3.  搜索工具
    * 维基百科
    * 知识图谱
    * 谷歌学术
    * and so on

---
## 信息搜索方向

### 大牛

Buzsaki
> *Rhythms of the brain*
> 2011年第一届Brain Prize的三位获奖者之一

Brenda Langford
> 神经心理学创始人
> 2005年的获唐纳德·赫布（Donald Olding Hebb）奖，2009年的巴尔赞（Balzan）认知神经科学奖，2014的卡弗里（Kavli）神经科学奖
> 沟通神经科学与心理学、开创认知神经科学的关键人物
> [布伦达·米尔纳](https://mp.weixin.qq.com/s/T-SupOg2W0rC9l4yQBWs_g)
> [廉价、高质量记录设备的出现和深度学习的成熟为神经科学提供了绝妙的机会](https://www.simonsfoundation.org/2018/08/03/systems-neuroscience-is-about-to-get-bonkers/)

Hinton 神经网络
> 知识局限暂时不清楚和神经科学之间的关系是怎样，后期很可能删掉

Jeff Hawkins 
> 计算机科学家 神经生物学家
> 千脑智力理论

### 实验室
最小策略：[阳志平网志](https://www.yangzhiping.com/)提到的
更全局策略：谷歌学术 牛人排名 → 实验室
比如：
> [【Neuron杂志30周年特刊】业内大牛综述，神经生物学前沿进展。](https://www.cell.com/neuron/current)

### 国际会议
策略：用谷歌学术的大牛排名间接搜索其参与/主持的会议

### 关键文献
顶级期刊综述
引用最高文献
学科排名前3大牛最重要文献
前沿进展，比如：
> [【Neuron杂志30周年特刊】业内大牛综述，神经生物学前沿进展。](https://www.cell.com/neuron/current)

---
## 执行策略

### 完成比完美重要
```
搜集 阅读 挖掘 闭环
优秀同侪
完成作品

```

**Comment by tsingyu42** [comment]
# 麦云飞的结业项目idea

我个人的希望是输出一份关于计算认知科学的全局认识。

这个全局认识经由回答这三个主要问题来生成。

1. 时间：计算机科学的发展脉络是什么？
2. 空间：计算认知科学的大牛有哪些？与计算认知科学密切相关的机构有哪些？
3. 变量关系：计算认知科学作为因变量的自变量是什么？计算认知科学作为自变量的因变量是什么？

---

以上是主要内容，以下是次要内容（我顺便把之后马上会涉及到的一些细节也一口气理了一下）。我们这次首先得定好方向，也就是确定好选题。

---

项目的起步阶段有个小矛盾：**欲了解计算认知科学，就需找出这个领域的大牛、机构、期刊。然而要找出计算认知科学的大牛、机构、期刊，则需要了解什么是计算认知科学。**毕竟计算认知科学还不像它的母亲（计算机科学、心理学，等）那样已成为显学，所以这个主题内的事物很难通过简单步骤就搜寻出来。

交织、闭合的矛盾问题并不难下手。那么该怎么解决呢？我的想法是最小行动先行——做出有效的初始行动。先搓一个小雪球，然后让它越滚越大。

要解决那个*小矛盾*，起点无非二选一：先认识计算认知科学，再去依此寻找大牛。或是先初步判定一些大牛，再依此去认识计算认知科学。（需要辨析的是，这指的是初始启动的行动。在整个信息分析、完成BP的过程中，认识科学和认识人的过程会轮转几次。也就是发展运动的螺旋上升，好吧有点哲学。总之，略唠叨的这段话是为了指出不需要在这一个点上纠结太久。）

我觉得马上就从「人」下手的话，范围太大容易迷失。还是需要稍微先约束一下什么是「计算认知科学」。

我目前想到的线索是：①维基百科；②阳老师博客关键词搜索；③老师相对推崇的侯世达及其著作。从里面初步获取一些相关人物和核心话语，然后就可以展开信息获取工作了。（第二周的课程提到：获取人工智能的千篇论文，光靠`人工智能`这个词并不能较精确地集中全局，还需要`神经网络`、`深度学习`等keywords，即人工智能领域的核心话语）

补充个④TED、YouTube。不过这个在初次限定范围之后进行，用于相对正式地确定认知计算科学的范围。

# 结业项目流程

1. 敲定方向
2. 选定组长（去讨论区上一休的结业项目登记帖子上报到）
3. 展开 行动/需输出内容 的清单，然后分工承包
4. 输出文件，合成项目（信息分析过程）
	* 信息获取：初次限定领域 → 正式限定领域 ＆ 收集文献、阅读书籍
	* 信息整理：zotero共享目录、GitHub（自己建的仓库里的）awesome清单
	* 信息加工：输出卡片、输出小文章
	* 信息报告：输出PPT
5. 路演准备
	* 提交demo
	* 提前压力测试，不断迭代

**Comment by tsingyu42** [comment]
理解刘旭同学的思路，其实我最初也是这种表达。不过上周三阳老师答疑中已经提及了最小知识原则和最小全局认识的关系：这两个其实没有什么关系，不过是解答同一类问题的两种不同模型罢了。因为在信息分析课程的框架下，所以我后来就改成用「全局认识」的框架来生成/表达自己的思想了。用「最小知识原则」和「最小全局认识」都无所谓，这两个都是阳老师的高阶模型，在学术情景下是通的。这些都是相对细节的内容。

**目前我们需要敲定或者说，确认下来的，是项目的topic。**目前我和刘旭同学想探索的是计算认知科学，王婧靖同学想探索的是认知神经科学，这里出现了差异。所以我抛砖引玉地提出我的想法：所以我们确认我们的结业BP是输出计算认知科学与认知神经科学这两个二级学科的全局认识吗？如果是的，我们还可以寻找一下这两个学科之间联系。总之，确认一个基本topic之后，就可以去一休那里报到了。

以及 @xdpwjj 神经网络应该是人工智能里的术语。不过阳老师说人工智能跟计算认知科学是两码事。

另外，我得完善一下上一层楼的内容了。（一开始以为讨论idea指的是确定好topic，还没到开始展开的地步）

**Comment by zapp926** [comment]
> 目前我和刘旭同学想探索的是计算认知科学，王婧靖同学想探索的是认知神经科学，这里出现了差异。

认知神经科学和计算认知科学，我目前的认识是没法很明确的区分，只有一个很模糊的边界。这个我还在探索中。

> 以及 @xdpwjj 神经网络应该是人工智能里的术语。不过阳老师说人工智能跟计算认知科学是两码事。

神经网络在人工智能和计算认知科学都会使用到的，我理解的区分「人工智能」和「计算认知科学」是面对的对象不同，人工智能的对象是机器，计算认知科学是人，因为计算认知科学是建立模型，模拟人的认知过程和心智，最后的实际结果仍然需要找被试做实验进行模型验证。所以贝叶斯、深度学习、SVM、神经网络在计算认知科学中同样会使用。

@MaiYunfei2000

**Comment by tsingyu42** [comment]
@zapp926 原来如此，好的了解了。

**Comment by zapp926** [comment]
@MaiYunfei2000 

* 已看过，整理的很详细，很棒。咱们到0101把汇总的资料放到一块，就能分别从时间、空间、变量关系三个角度或者其它的分工方法继续探索了。

* 我大致翻了一下侯世达的「我是个怪圈」，内容很难理解，不知道「心智建模」能不能看成对计算认知科学的通俗解释。

* 有趣度方面或文献方面能不能额外从science创刊125周年提出的三个心理学问题看看会有什么意外的发现，这些问题是不是需要使用计算认知科学建模才能找到近似解。[科学通报的解读](http://wap.sciencenet.cn/home.php?mod=space&uid=528739&do=blog&quickforward=1&id=1029192)

**Comment by zapp926** [comment]
@MaiYunfei2000 
 
现在是寒假，暑假时候非常推荐你关注一下「北京大学暑期学校」，推荐李量老师的课，「意识的脑机制」、「视听言语加工的脑机制」、「暴力的脑机制」. 我们暑假专门研究了意识的话题，得到的一些想法是从「信息整合平台论」「内噪声」等角度去理解意识的。

**Comment by zapp926** [comment]
> 学问有个特征比有没有用更重要，那就是美不美。— 马奇

通过大作业如何体现出学术的美感？？？

**Comment by tsingyu42** [comment]
> 现在是寒假，暑假时候非常推荐你关注一下「北京大学暑期学校」，推荐李量老师的课，「意识的脑机制」、「视听言语加工的脑机制」、「暴力的脑机制」. 我们暑假专门研究了意识的话题，得到的一些想法是从「信息整合平台论」「内噪声」等角度去理解意识的。

好的，谢谢

**Comment by tsingyu42** [comment]
> 通过大作业如何体现出学术的美感？？？

好问题。不过这个可以放在最后的项目输出阶段来思考。
