### ISSUE TITLE
Introduction of *The Cambridge Handbook of Computational Psychology*

### ISSUE THREAD

**Issue by xdpwjj** [MaiYunfei2000/IA003CoCoSci#11]
# The Cambridge Handbook of Computational Psychology

- discusses the general methodology of computational cognitive modeling
- justiﬁes its use in cognitive science and beyond

## keywords

- computational cognitive modeling 计算认知建模
- algorithmic speciﬁcity 算法特性
- model of cognition 认知模型
- hybrid connectionist-symbolic systems ？

## model (see, e.g., Bechtel & Graham, 1998)

- Connectionist Models
- Bayesian Models
- Dynamical Systems Approaches
- Declarative/Logic-Based Cognitive Modeling
---

- computational model 计算模型 `主要`
- mathematical model 数学模型
- verbal-conceptual model 语言概念模型

>  Computational models present process details using algorithmic descriptions. Mathematical models present relationships betweenvariablesusingmathematicalequations. Verbal-conceptual models describe entities, relations, and processes in rather informal natural languages. Each model, regardlessofitsgenre,mightaswellbeviewed as a theory of whatever phenomena it purports to capture (as argued before by, e.g., Newell, 1990; Sun, 2005).

### 1.What is computational cognitive modeling?

- A computational model may often be viewed as a theory of the phenomena it aims to capture and may be highly intellectually enlightening in this way. 
- process-based theories（基于过程理论） ？
- computational model may lie somewhere along the continuum from pure product theories to pure process theories

> 1970s, a variety of inﬂuential symbolic “cognitive” models were proposed in artiﬁcial intelligence.  Many computational cognitive models were inspired by symbolic AI work at that time (Newell & Simon, 1976).
 
### Conferences

- Annual Conferences of the Cognitive Science Society 
- International Conferences on Cognitive Modeling 

### Journal

- Cognitive Science
- Cognitive Systems Research 

### Person

- Newell

###  software, tools, models, and systems 

- http://www.cogsci.rpi.edu/∼rsun/arch.html
- http://books.nap.edu/openbook.php?isbn=0309060966
- http://www.isle.org/symposia/cogarch/archabs.html.

 speciﬁc
- http://psych.colorado.edu/∼oreilly/PDP++/PDP++.html
- http://www.cogsci.rpi.edu/∼rsun/clarion.html
- http://act-r.psy.cmu.edu/
- http://sitemaker.umich.edu/soar/home
- http://www.eecs.umich.edu/∼kieras/epic.html

### timeline

-  **symbolic “cognitive” models** were proposed in artiﬁcial intelligence.
> They were usually broadandcapableofasigniﬁcantamountof informationprocessing.However,theywere usually not rigorously matched against humandata.Therefore,itwashardtoestablish thecognitivevalidityofmanyofthesemodels. 

- **neural network models** in the 1980s 
> Instead of symbolic models that rely on a variety of complex data structures that store highly structured pieces of knowledge (such asSchank’sscriptsorMinsky’sframes),simple, uniform, and often massively parallel numerical computation was used in these neural network models (Rumelhart et al., 1986). Many of these models were meant to be rigorous models of human cognitive processes, and they were often evaluated in relation to human data in a quantitative way.

- **Hybrid models** that combine the strengths of neural networks and symbolic models emerged in the early 1990s
> Such models could be used to model a wider variety of cognitive phenomena because of their more diverse and thus more expressive representations.

## Chanpter 2 Connectionist Models of Cognition(page 37-65)

[Artificial neural networks (ANN) or connectionist systems wikipedia](https://en.wikipedia.org/wiki/Artificial_neural_network#History)

参考
- 机器之心 https://www.jiqizhixin.com

**update to page 135 and to be continued**

changelog

- 190114 2144 wjj add details of chapter 4
- 190114 1105 wjj add introduction of chapter 4
- 190112 0131 wjj add notes of introduction of handbook

**Comment by tsingyu42** [comment]
棒👍🏻不过这里是一张卡片还是多张卡片[#疑惑]

**Comment by xdpwjj** [comment]
> 棒👍🏻不过这里是一张卡片还是多张卡片[#疑惑]

- 不是一张也不是多张，还没有成型，暂时记录在这里
- 也是能让大家看到更新进度

**Comment by zapp926** [comment]
ZAPP杂七杂八补充：
* 
![](https://ws1.sinaimg.cn/large/006tNc79ly1fz6g8xio0jj313x0eo75l.jpg)

* [心智:认知科学导论](https://www.amazon.cn/dp/B008GANFG2 )

* [paper-新一代人工智能的核心基础科学问题：认知和计算的关系](http://www.cas.cn/zjs/201811/P020181128534006854889.pdf)

**Comment by zapp926** [comment]
[中国认知科学学会](http://www.cogsci.org.cn)

**Comment by tsingyu42** [comment]
connectionism是「联结主义」，认知心理学的一个术语。symbolism，「符号主义」。

**Comment by xdpwjj** [comment]
## CHAPTER 4 Dynamical Systems Approaches to Cognition(page 116-137) 认知的动力系统方法

### Introduction

The view of cognition emphasizes the close link of cognition to the sensory and motor surfaces and the structured environments in which these are immersed. 
认知观强调认知与感觉和运动曲面以及这些曲面所处的结构环境之间的密切联系。
**The dynamical systems approach to cognition is the theoretical framework within which this embodied view of cognition can be formalized.
认知的动力系统方法是使这种具体的认知观形式化的理论框架。**
how cognition can be understood that are compatible with principles of neural function
认知过程和神经功能原理过程一致的时空连续性。

###  Embodiment, Situatedness, and Dynamical Systems

- Body receives sensory information and acts in a speciﬁc, structured environment on which it may have an effect.
身体从外界环境获得感知信息，并对环境作出反应
- Body and nervous system are adapted to natural environments on many time scales.
身体和神经系统在多个时间尺度上适应环境
- element related to cognition
    - the linkage between cognitive processes and the sensory and motor surfaces
    - the structured environments in which cognition takes place
    - individual experience in cognition
    - the concrete neuronal processes

#### Dynamical systems theory about cognition
- Dynamical systems theory provides the **language** in which the **embodied and situated stance** can be developed into a scientiﬁc theory of cognition. 
动力系统提供了一种语言，通过这个语言的形象化和所处立场可以构建一种认知理论
- Scientiﬁc theories based on this mathematical framework have been extraordinarily successful in physics and many branches of science connected to physics. 
基于数学框架的动力系统已经在物理学科等领域取得成功
-  By analogy, developing an understanding of cognition within the mathematical framework of dynamical systems requires that concepts are deﬁned that bring the mathematics to bear on the subject matter. 
但是在认知领域，只有数学框架是不够的，我们需要再次框架内定义概念，使数学框架与主题相契合。
- In summary，to form concepts based on the mathematical theory of dynamical systems into a rigorous scientiﬁc approach toward cognition that embraces the embodied and situated stance. 
总结来说，以动力系统的数学理论为基础形成一种包含情景的认知的科学方法。

### Dynamical Systems Thinking

- Control systems provide an interesting metaphor for the notion that meaningful function may emerge from simple, embodied mechanisms

> A highly illustrative example comes from the orientation behaviors of the common house ﬂy. Flies orient toward moving objects, which they chase as part of their mating behavior.

When a control system makes decisions, selects among a range of inputs, and generates behavior basedonitsowninnerstate,thenthismight represent the most elementary form of cognition.

> The ﬂight control system of house ﬂies is capableofsuchﬂexibility.Whenconfronted with several patches of visual motion on its facet eye, the ﬂy selects one of the patches and directs its ﬂight in pursuit of that visual object,This capacity to select emerges from the control dynamics. Superposing the torque patterns dynamical systems approaches to cognition 105 generated by each motion patch, two attractors emerge (Fig. 4.1c). One of these is selected depending on the initial orientation and on chance. When the two patches are close to each other, the two attractors merge, and the ﬂy ﬂies in an averaged direction (as shown in Fig. 4.1b). 

the principles of adynamic approach to behavioral patterns

 1. Patterns of behavior are characterized by inner states
 2. The evolution in time of these state variables is generated by neural networks
 3.  Asymptotically stable states structure the solutions of this dynamical system
 4.  Behavioral ﬂexibility arise when states are released from stability


 
### Discussion 
- if approach embrace the theoretical stance of embodiment and situatedness
- if the dynamical systems approach take seriously the link of cognitive processes to sensory and motor processes
- if embedding of cognition within structured environments and behavioral history of an organism

#### 1.Embodied
- Autonomy 
    - Cognition in naturalistic settings based on autonomy 
    - continuous ﬂow of experience under both the **action of the individual** and the **timevarying sensory information about a changing environment**
- Stability
    - The theoretical concept of stability is key to understanding autonomy
    - cognitive processes link to the on-line sensory input and motor system
    - Instabilities are crucial for understanding how the discrete behavioral events may emerge 
- The exploration of cognitive model
     - To implement the models on physical robotic platforms
     - Dynamical systems thinking has been tested with robot icimplementations
- The application field of dynamical system thinking

#### Dynamical Systems Approach and its neurally Based
- Biophysically, neurons are little dynamical systems
- The two branches of dynamics systems thinking roughly mapped onto two forms of neuronal coding: rate coding and space coding

**Comment by xdpwjj** [comment]
chapter 5  Declarative/Logic-Based Cognitive Modeling(page 142-180)
https://github.com/MaiYunfei2000/IA003ComputationalCognitiveScience/issues/17#issuecomment-455839603

**Comment by xdpwjj** [comment]
维基百科：
逻辑
人工智能领域用逻辑来理解智能推理问题；它可以提供用于分析编程语言的技术，也可用作分析、表征知识或编程的工具。目前人们常用的逻辑分支有命题逻辑（Propositional Logic ）以及一阶逻辑（FOL）等谓词逻辑。
机器之心：
逻辑编程的最初想法是，你应该告诉计算机什么是正确的。给定这个真实的事实和规则数据库，逻辑推理可以用来回答用户的查询。这种编程风格被称为“声明式编程”（declarative programming）。它描述目标的性质，让计算机明白目标，而非流程。声明式编程不用告诉计算机问题领域，从而避免随之而来的副作用。声明式编程通常被看做是形式逻辑的理论，把计算看做推导。声明式编程因大幅简化了并行计算的编写难度，自 2009 起备受关注。

## CHAPTER 5 Declarative/Logic-Based Cognitive Modeling(page 142-180)

[参考](https://mp.weixin.qq.com/s?__biz=MzU1NDA4NjU2MA==&mid=2247491161&idx=3&sn=960787f03f911d8faeacf90335da328e&scene=0#wechat_redirect)

### 1.Introduction

#### 1.1 What Is Logic-Based Computational Cognitive Modeling(LCCM)? 

- 本章是用声明式计算认知模型（Declarative Computational Cognitive Modeling）对心智建模。
- 模型的基本单元是声明式或命题式的。
- 单元的基本过程是推理，也可以是演绎、归纳、概率、溯因或类比。
- Declarative computational cognitive modeling is a top-down, rather than bottom-up, approach. 声明式计算认知建模一个标志是自上而下的方式，而非自下而上。
- 使用形式逻辑实现

1.2. Level of Description of LCCM

- LCCM 是一种框架，类似于使数学系统化的框架
- 声明式计算认知建模基本是用逻辑系统和基于逻辑的计算机程序来建模的
- 系统化的框架为声明式计算认知体系提供了一种理解方法，基于规则、显式逻辑、论证、命题、规则的计算认知体系
- 建立在数学逻辑中的概念

1.3. The Ancient Roots of LCCM （three challenges）

Declarative computational cognitivemodeling is the oldest paradigm for modeling the mind. Over 300 years b.c., logic and logic alone was being used to model and predict human cognition.  声明式计算认知模型是最古老的表征思维的范式。公元前300年人们已经开始使用逻辑学来建模和预测。

>  For example, consider the following argument:（经典三段论）
(1) All professors are pusillanimous people. 
(2) All pusillanimous people are proud. 
∴ (3) All professors are proud. 
Thesymbol∴,oftenreadas“therefore,”says that statement (3) can be logically inferred from statements (1) and (2); or in other wordsthatifstatements(1)and(2)aretrue, then (3) must be true as well.

> (1∗) AllAs are Bs. 
(2∗) AllBs are Cs. 
∴ (3∗) AllAs are Cs. 

三段论的局限：

- 有的人不能正确推理
- 三段论只是逻辑体系的一小部分

1.4. LCCM’s Sister Discipline: Logic-Based Human-Level AI （略）

1.5. Different Levels of Description （略）

1.6. Brief Overview of the Three Challenges 

- Challenge 1: Human reasonin 人类推理
- Challenge 2: 自Newell发展起来的很多种不同的计算认知架构，但是他们的计算能力都比较有限。有两个原因：核心机制不足以表征人类思维复杂度。我们需要一种核心机制，这种机制能够实现高维度的推理和元分析以及对外部环境的感知和操作。
- Challenge 3: 大多数计算认知结构都没有清晰精确的语法，而计算认知建模还没有像物理数学计算机那样的清晰准确的语言和定理

### 2. The Goal of Computational Cognitive Modeling/LCCM

声明式计算认知模型是通过在信息处理系统中建模来理解人的特有认知类型。
LCCM致力于：
1. 做出选择、决定的自由意志
2. 对经历的主观感受
3. 自我意识
4. 语言交流
5. 了解和相信
6. 对实践改变的渴望
7. 推理

### 3. LCCM面里的3大挑战

- 对强大的人类推理能力模仿的无能
- 用一种全面的理论语言统一认知
- 计算认知模型缺乏成熟的数学计算能力（计算认知模型是认知的，没有形成成熟的定理）

### 4. Logic-Based Computational Cognitive Modeling （略）

### 5. Meeting the Challenges

- 契合人类推理
- 建模实现知觉/行动的高级推理

changelog

- 190121 0656 wjj add chapter 5

**Comment by tsingyu42** [comment]
逻辑的话能不能找到里程碑论文？
