### ISSUE TITLE
卡片库|人名卡

### ISSUE THREAD

**Issue by tsingyu42** [MaiYunfei2000/IA003CoCoSci#12]

**Comment by tsingyu42** [comment]
## 约翰·安德森（John R. Anderson）

美国心理学家，卡内基梅隆大学的心理学和计算机科学教授。在认知心理学中，因其认知架构（cognitive architecture）ACT-R和理性分析（rational analysis）而广为人知。

1968年获得不列颠哥伦比亚大学文学学士学位，1972年获得斯坦福大学心理学博士学位。 1972年，他成为耶鲁大学的助理教授。 1973年，他以初级研究员的身份进入密歇根大学，并与研究生 Lynne Reder 结婚。1976年，他以终身教职的身份回到了耶鲁大学。 他在1977年被提升为耶鲁大学的全职教授，但在1978年被调到卡内基梅隆大学。 从1988年到1989年，他担任认知科学学会主席。 

他被选入美国艺术与科学学院和美国国家科学院，并获得了一系列奖项: 
* 1968: Governor General's Gold Medal: Graduated as top student in Arts and Sciences at University of British Columbia
* 1978: Early Career Award of the American Psychological Association
* 1989–1994: Research Scientist Award, NIMH
* 1994: American Psychological Association's Distinguished Scientific Career Award
* 1999: Elected to the National Academy of Sciences[1]
* 1999: Fellow of American Academy of Arts and Sciences[2]
* 2004: The David E. Rumelhart Prize [3] for Contributions to the Formal Analysis of Human Cognition
* 2005: Howard Crosby Warren Medal for outstanding achievement in Experimental Psychology in the United States and Canada, Society of Experimental Psychology
* 2006: Inaugural Dr. A.H. Heineken Prize[4] for Cognitive Science awarded by the Royal Netherlands Academy of Arts and Sciences
* 2011: Benjamin Franklin Medal in Computer and Cognitive Science, Franklin Institute[5] "for the development of the first large-scale computational theory of the process by which humans perceive, learn and reason, and its application to computer tutoring systems."
* 2016: Atkinson Prize from the National Academy of Sciences.

**Comment by tsingyu42** [comment]
## 约书亚·布雷特·特南鲍姆（Joshua Brett Tenenbaum）

约书亚 · 布雷特 · 特南鲍姆是麻省理工学院脑与认知科学系的教授，麻省理工学院[计算认知科学小组](http://cocosci.mit.edu/people)的领头人。 他因对数学心理学（[mathematical psychology](https://en.wikipedia.org/wiki/Mathematical_psychology)）和贝叶斯认知科学（[Bayesian cognitive science](https://en.wikipedia.org/wiki/Bayesian_cognitive_science)）的贡献而闻名。他的主要工作是将分析概率推理(analyzing probabilistic inference)这个工具用于认知建模和发展机器学习理论。

约书亚是互联网商务先驱杰伊 · 马丁 · 特南鲍姆的儿子。他于1993年获得耶鲁大学物理学本科学位，1999年获得麻省理工学院博士学位。他曾在斯坦福大学任教，2010年10月至2011年1月期间担任沃索访问学者。

**Comment by tsingyu42** [comment]
## 詹姆斯·麦克莱兰（James L. McClelland, or Jay McClelland）

詹姆斯 · 劳埃德 · 麦克莱兰，斯坦福大学露西 · 斯特恩教授，英国人文社会科学院通讯院士。他曾任斯坦福大学心理学系主任。 他最著名的工作是统计学习和并行分布式处理，应用连接主义模型(或神经网络)来解释认知现象，如口语单词识别和视觉单词识别。 20世纪80年代，联结主义引起了科学界的极大兴趣，麦克莱兰在很大程度上与此有关。

**Comment by tsingyu42** [comment]
## 塞尔默 · 布林斯乔德（Selmer Bringsjord）

塞尔默(生于1958年11月24日) ，伦斯勒理工学院认知科学系主任，计算机科学和认知科学教授。 他还在拉里管理和技术学院任职，教授人工智能、形式逻辑、人类和机器推理以及人工智能哲学。他专门研究人工智能和认知科学的逻辑、数学和哲学基础，并在计算逻辑的基础上合作构建人工智能系统。

**Comment by xdpwjj** [comment]
以人名、期刊、奖项、会议单独建立issue看起来更清楚呢

**Comment by xdpwjj** [comment]
## Allen Newell

看了以上几个人名是剑桥手册的主要contributor，按照此思路找到书中多次提及及引用文献的人，**Allen Newell**
- 交叉验证此人是1975年图灵奖获的者（另一位是西蒙）
- 再次交叉验证用Acemap发现Allen和Simon是紧密的合作者

**Comment by tsingyu42** [comment]
@xdpwjj 

> 以人名、期刊、奖项、会议单独建立issue看起来更清楚呢

其实那些只是顺带复制下来的……假如要展示出来的话我只打算留第一段……

至于人物的话你看一下最新的引文关系的帖子，以及谷歌表格，就一下明白了。人物和机构这边我已经完成了（可能需要增补个别人物）。

所以集中精力输出最小话语体系吧~
