### ISSUE TITLE
卡片库|学者引文网络

### ISSUE THREAD

**Issue by tsingyu42** [MaiYunfei2000/IA003CoCoSci#14]

**Comment by tsingyu42** [comment]
**约翰·安德森**

![image](https://user-images.githubusercontent.com/40352237/51310776-5d9aaf80-1a82-11e9-8982-4b6e7845964f.png)

**Comment by tsingyu42** [comment]
**约书亚·特南鲍姆**

![image](https://user-images.githubusercontent.com/40352237/51310977-d13cbc80-1a82-11e9-92a9-734e3d32d8c9.png)

**Comment by tsingyu42** [comment]
**詹姆斯·麦克莱兰**

![image](https://user-images.githubusercontent.com/40352237/51311187-4a3c1400-1a83-11e9-9e9f-7c35bdd6330a.png)

**Comment by tsingyu42** [comment]
**塞尔默·布林斯乔德**

![image](https://user-images.githubusercontent.com/40352237/51311285-82dbed80-1a83-11e9-9179-7852d6a7c277.png)

**Comment by xdpwjj** [comment]
![image](https://user-images.githubusercontent.com/18694954/51311870-e61a4f80-1a84-11e9-8908-244fea14afb9.png)

**Comment by tsingyu42** [comment]
@xdpwjj 纽厄尔和西蒙是人工智能和认知心理学那边的，不是我们此次要探索的人物。

**Comment by xdpwjj** [comment]
@MaiYunfei2000 
Alright.

**Comment by tsingyu42** [comment]
Gregor Schoner/Gregor Schöner
格雷戈·舍那（德国名，怪怪的）

![image](https://user-images.githubusercontent.com/40352237/51444013-c0af6f00-1d2c-11e9-9955-2d5dab33ed4f.png)
