### ISSUE TITLE
ZAPP卡片输出

### ISSUE THREAD

**Issue by zapp926** [MaiYunfei2000/IA003CoCoSci#15]
### ZAPP补充：
* http://www.flinders.edu.au/science_engineering/csem/research/programs/cabs/cabs_home.cfm
* http://cocolab.stanford.edu/resources.html
* http://psiexp.ss.uci.edu/research/madlab.htm
* https://ruccs.rutgers.edu/jacob

* [吴思](http://imibr.bnu.edu.cn/a/zh/keyantuandui/jiaoshou_yanjiuyuan/2016/0223/621.html)
[吴思](http://mgv.pku.edu.cn/yjdw/aszyxck/xxjzkxxy/266415.htm)

商业机构
* 国外
    * https://deepmind.com/

    * https://www.simonsfoundation.org/

* 国内
    * 北京心智计算科技有限公司

国内暑校

* http://www.ccnss.org/

### ChangeLog
* 190117 ZAPP创建

**Comment by zapp926** [comment]
思路先来两三页幻灯介绍认知科学，从认知科学这个一级学科切入到计算认知科学这个二级学科。

1、引子：用来强调认知科学的重要性。所以我们关注的计算认知科学是很有前途的一个领域。

* 21世纪初，美国国家科学基金会和美国商务部共同资助了一个雄心勃勃的计划 —— “提高人类素质的聚合技术”，将纳米技术、生物技术、信息技术和认知科学看作21世纪四大前沿技术，并将认知科学视为最优先发展的领域，主张这四大技术融合发展，并描绘了这样的科学前景：聚合技术以认知科学为导向，因为一旦我们能够在如何（how）、为何（why）、何处（where）、何时（when）这四个层次上理解思维，我们就可以用纳米科技来制造它，用生物技术和生物医学来实现它，最后用信息技术来操纵和控制它，使它工作。

2、然后介绍认知科学目前的发展状况。四大趋势中，第二个趋势是我们的计算认知科学。

* 认知科学当前发展的四大趋势：
    * 第一个趋势：认知神经科学对于所有的心理学分支都变得越来越核心。
    * 第二个趋势：基于贝叶斯概率理论等统计模型变得日益重要。
    * 第三个趋势：对具身性越来越多的强调。
    * 第四个趋势：对认知的社会维度的更多理解。

3、介绍认知科学的研究方法，我们使用的是第三种方法，计算机模拟。

* 认知科学家有四种手法来研究人类的认知：思想实验；实验科学；计算机模拟；人类学调研。

4、这样就引出我们的主角。「计算认知科学」

* 认知科学研究人类感知、学习、记忆、思维、意识等人脑心智活动过程，而计算认知科学使用神经计算模型来探索大脑信息加工的认知过程和神经机制，从而建立物理可实现的计算模型。计算认知科学的出发点是：认可思维是心理表征以及在这些表征上的计算过程的操作结果，假设是以计算隐喻为核心。

这些内容介绍完，不会占用太多时间，组织好语言不会出现抢主角的问题。

**Comment by zapp926** [comment]
约翰·罗伯特·安德森（John Robert Anderson, 1947.08.27－）美国著名认知心理学家，美国卡内基梅隆大学心理学系和计算机科学系梅隆教授，美国科学院院士。著有「认知心理学及其启示」，以其认知架构 ACT-R 广为认知。

2004年，著名心理学史家 Noel Sheehy 将约翰·安德森与冯特、弗洛伊德、巴浦洛夫以及西蒙并列，评定他为人类历史上「50位最伟大的心理学思想家之一」，而且是其中最年轻的一位。

**Comment by zapp926** [comment]
ACT-R 「思维的自适应控制」是著名认知心理学家安德森组织开发的一种认知仿真工具，能够模拟人的一些认知活动。它依据大量的认知心理学实验，其仿真结果得到真人实验和核磁共振实验的验证。目前使用这种认知工具已经成功地模拟了多种认知任务，如汉诺塔、模式识别、记忆、数学的认知过程等。

ACT-R 可用来描述关于人类认知过程的工作机制，可以实现对特定任务的认知模型构建。利用 ACT-R 内建的认知理论加上特定任务的必要假设和知识描述，可以构造特定任务的 ACT-R 认知体系模型，以解决某一实际问题。

![](https://ws1.sinaimg.cn/large/006tNc79ly1fzcnphf28ej30e50950sx.jpg)

**Comment by tsingyu42** [comment]
good

**Comment by zapp926** [comment]
结尾可参考这张两图片给我咱们的反思：

![](https://ws4.sinaimg.cn/large/006tNc79ly1fzcvsj75cwj30sa0k2q3r.jpg)
![](https://ws3.sinaimg.cn/large/006tNc79ly1fzcvshbee7j30ri0jdgnj.jpg)

* 对这个学科的反思
    * 心智是一个动力学系统，而非计算系统。计算认知忽略了情绪对认知的重要作用，具身认知影响。

**Comment by zapp926** [comment]
结尾的倒数第三张幻灯可以这样来布局：

* 通过我们的一个最小全局认识，认识到了认知科学的挑战以及广阔的前景，我们清楚的看到这里有很多生机勃勃、充满希望的研究前沿。如果你有志于探索人类的心智，我们的建议如下：
    * 挑选出心智中你最感兴趣的一个方面。e.g., 语言、推理、记忆、情绪 etc. 你觉得思维的哪些方面对你最有吸引力。
    * 挑选一种研究方法。「前面我们讲到：认知科学家有四种手法来研究人类的认知：思想实验；实验科学；计算机模拟；人类学调研。」想想哪一种研究最适合你的兴趣和天分？你觉得进行实验设计还是计算机编程更让容易让你产生心流？你是喜欢收集人类学案例还是喜欢像哲学家那样思考心智的问题？如果你像我们一样喜欢「计算认知科学方向」，我们看好的是「贝叶斯流派」。
    * 在做自己领域研究的同时，注意留心其它领域的进展。当今时代学科交叉已是趋势，用一个学科的方向来解决另一学科的问题亦是常态，所以不能忽视与其它领域之间的有趣联系。同时要注重整合与协作。在科研上应保持开放的态度，如即进行实验研究也利用计算机模拟。在认知科学中不少优秀的工作都是综合了不同的学识见解和方法轮研究者的合作完成的。
    * 最后要强调的最重要的一点是「学问有个特征比有没有用更重要，那就是美不美。— 马奇」P.s. 可以顺便放上一张很漂亮的大脑神经的图片。
* 如果你想申请国外「计算认知科学」方向的硕博，请参考我们的「awesome-list」。

**Comment by zapp926** [comment]
结尾的倒数第二张幻灯：

* 计算认知科学资源「awesome-list」......

**Comment by zapp926** [comment]
结尾的倒数第一张幻灯：

* Q&A
* 谢谢大家

**Comment by zapp926** [comment]
补充前面的内容：

* 来自集智俱乐部的PDF文档，摘取有用的部分。

* 对于用计算模型理解人类认知这个研究领域，认为自己是从事心理学研究的称之为计算心理学，认为自己是从事认知科学研究的称之为计算认知科学，认为这个领域还不够成熟不足以成为一个独立学科的称之为计算认知建模。最基本的计算认知模型是基于符号逻辑的（如产生式系统）和基于连接主义的（如神经网络），可以看到，这两种模型分别对应于 AI 的两个主要派别 – 符号/逻辑主义和连接主义。近年来也发展出了一些新的模型，如我们这学期将要讨论的贝叶斯模型等等。计算认知科学最宏大的目标是构建出一个能把认知心理学中各种零散的实验现象和理论综合起来的普适的统一认知理论，当前的进展离这个目标还很远，而且，这个目标看起来似乎与强 AI 的目标一样遥不可及。但无论怎样，在通往这个也许永远也不会到达的目标的探索路途上，我们总会对大脑和认知有着越来越深入的理解，也会对我们要探索的问题有越来越精确的认识。也许永远不可能实现强 AI，但总可以使弱 AI 越来越强大。每种计算模型都有各自的缺陷和局限性，讨论已有模型的缺点不是为了否定这些模型，而是为了构建出更好的模型。很可能不存在一种单一计算模型能对所有认知活动建模，大脑的活动是很多不同模型同时运作相互影响的过程。即使不能弄明白所有的认知活动，仅分析清楚单个认知活动也是有意义的，比如，如果能模拟人的记忆功能，对信息检索和搜索引擎将有无法估量的重大价值。

**Comment by tsingyu42** [comment]
差点忘了，我们要在后面提出：我们这次的信息分析的基本目的是弄清计算认知科学的时间源头，整理一个信息工具箱。以及，我们打算基于这次探索，在国内的学界套利——中期的目标是在国内的刊物上发表综述论文。

在这里码一下免得自己忘了。

**Comment by tsingyu42** [comment]
引子里的“它”是指什么？

**Comment by tsingyu42** [comment]
> 第二个趋势：基于贝叶斯概率理论等统计模型变得日益重要。

在展示给大众时变成“各种计算模型变得日益重要”或是“各种计算模型——例如基于贝叶斯概率论的模型——变得日益重要”？

**Comment by zapp926** [comment]
> > 第二个趋势：基于贝叶斯概率理论等统计模型变得日益重要。
> 
> 在展示给大众时变成“各种计算模型变得日益重要”或是“各种计算模型——例如基于贝叶斯概率论的模型——变得日益重要”？

ok

**Comment by zapp926** [comment]
> 引子里的“它”是指什么？

大脑 或者说心智、思维

**Comment by zapp926** [comment]
> 差点忘了，我们要在后面提出：我们这次的信息分析的基本目的是弄清计算认知科学的时间源头，整理一个信息工具箱。以及，我们打算基于这次探索，在国内的学界套利——中期的目标是在国内的刊物上发表综述论文。
> 
> 在这里码一下免得自己忘了。

时间源头这个说法不太妥当，可以说源头，因为咱们不仅了解了时间线，也有空间和变量，时间太局限在这个单一维度。这个学科的信息源头是不是合适一些？

**Comment by tsingyu42** [comment]
认知科学的当代发展趋势感觉有点陷入知识诅咒，特别第三第四个，念给观众听感觉会有不知所云的效果，能不能换成：

* 第三个趋势：越来越强调身体在认知中的作用，而不是仅仅盯着大脑或者心智。
* 第四个我还得想想

**Comment by tsingyu42** [comment]
> 时间源头这个说法不太妥当，可以说源头，因为咱们不仅了解了时间线，也有空间和变量，时间太局限在这个单一维度。这个学科的信息源头是不是合适一些？

那解决方法之一是，干脆就只用“源头”两个字，前面不加定语。
另外也可能是我们对时间源头的理解不同。这就要扯到《追时间的人》了。

**Comment by tsingyu42** [comment]
* 第四个趋势：越来越重视人类的社会性，而不是单独地去看一个人。

这样如何？

**Comment by tsingyu42** [comment]
其实用“时间源头”问题不大，这就是阳老师、安替老师他们创造的模因，产生于“时空选择论”的讨论中。我个人感觉“时空源头”更合适一点，不过他们都一直那样用着就算了。

这里的“时间”并不仅仅是历史，并不仅仅是时间。例如，“现在世界上有几个时间源头，例如北京，纽约和波士顿。”

但是这里的“时间”指的到底是什么呢？这个模因过于玄妙，你的想法也戳中了我的空洞，我发现自己其实没完全弄清楚这个概念，只知道怎么用它。我自己的水平只能让这流于形而上学的乱扯。

总之，此“时间”非彼“时间”。信分中的「全局认识」中的“时间”和「时空选择论」中的“时间”不是同一个概念。

**Comment by zapp926** [comment]
> 认知科学的当代发展趋势感觉有点陷入知识诅咒，特别第三第四个，念给观众听感觉会有不知所云的效果，能不能换成：
> 
> * 第三个趋势：越来越强调身体在认知中的作用，而不是仅仅盯着大脑或者心智。
> * 第四个我还得想想

跟着阳老师学的同学大部分都知道具身认知，或者你可以说「身体不是认知的外在，而是认知本身」。这些早在阳老师的博客中写出来了。你觉得怎么讲的舒服就怎么讲就行，不要去念稿，脱稿，内化这些知识然后对着幻灯讲。这样对你之后的讲演有帮助。

**Comment by zapp926** [comment]
> 其实用“时间源头”问题不大，这就是阳老师、安替老师他们创造的模因，产生于“时空选择论”的讨论中。我个人感觉“时空源头”更合适一点，不过他们都一直那样用着就算了。
> 
> 这里的“时间”并不仅仅是历史，并不仅仅是时间。例如，“现在世界上有几个时间源头，例如北京，纽约和波士顿。”
> 
> 但是这里的“时间”指的到底是什么呢？这个模因过于玄妙，你的想法也戳中了我的空洞，我发现自己其实没完全弄清楚这个概念，只知道怎么用它。我自己的水平只能让这流于形而上学的乱扯。
> 
> 总之，此“时间”非彼“时间”。信分中的「全局认识」中的“时间”和「时空选择论」中的“时间”不是同一个概念。

因为你没有「时空选择论」的背景，然后课程中一直强调「时间、空间、变量」，所以大家就很容易误解。

**Comment by tsingyu42** [comment]
> 跟着阳老师学的同学大部分都知道具身认知，或者你可以说「身体不是认知的外在，而是认知本身」。这些早在阳老师的博客中写出来了。你觉得怎么讲的舒服就怎么讲就行，不要去念稿，脱稿，内化这些知识然后对着幻灯讲。这样对你之后的讲演有帮助。

好的。

---

> 因为你没有「时空选择论」的背景，然后课程中一直强调「时间、空间、变量」，所以大家就很容易误解。

那就不加定语吧。

**Comment by zapp926** [comment]
计算认知科学的意义：推动认知科学走向「可计算性」，并将其带来的启发，应用在机器人、社交媒体与心理健康等广泛领域。— 阳志平「关于计算认知科学的随想」

你看下加在那里比较合适，它的意义还是要提的。
@MaiYunfei2000

**Comment by zapp926** [comment]
> > 跟着阳老师学的同学大部分都知道具身认知，或者你可以说「身体不是认知的外在，而是认知本身」。这些早在阳老师的博客中写出来了。你觉得怎么讲的舒服就怎么讲就行，不要去念稿，脱稿，内化这些知识然后对着幻灯讲。这样对你之后的讲演有帮助。
> 
> 好的。
> 
> > 因为你没有「时空选择论」的背景，然后课程中一直强调「时间、空间、变量」，所以大家就很容易误解。
> 
> 那就不加定语吧。

这个你看着讲吧，就是把我们都当成小白就行了。然后幻灯做好之后，尽管让几个观察员给把把关，因为咱们几个深陷其中，可能会造成思维定式，有的地方讲的过于深奥什么的。他们从一个旁观者的角度来审视，会有不一样的视角。

**Comment by zapp926** [comment]
关于计算认知科学的随想—阳志平

阳老师这篇博文是从下面这几个问题写的：
* 为什么要关注计算认知科学？也就是计算认知科学的重要性。这个咱们是从「聚合技术」的角度来切入的，是OK的。

* 计算认知科学的研究特色。
    * 使用算法（目前热门是机器学习中的神经网络的深度学习、贝叶斯）建模人类心智存在，并使用传统心理科学行为实验方法与证据予以校验。
    * 这个咱们介绍完认知科学的研究方法，我们使用的是第三种方法计算机模拟，之后谈一下计算认知的特色，相比于其它三种方法，就可以了。


* 计算认知科学的实践意义。这个改改阳老师的原话就行。

* 计算认知科学的位置。这个问题也可以稍微提一下。

这样也是从四个角度全面立体的了解计算认知科学这个学科，并且约束在四个。

**Comment by tsingyu42** [comment]
第一代认知科学始于50年代，就是西蒙、纽厄尔那帮人建立的，提倡「认知即计算」、「符号即表征」，被称为符号主义，它是基于的计算隐喻。

联结主义对符号和计算所持的立场与传统的符号主义信息加工心理学有所不同。联结主义认为认知过程不是简单的符号计算，而是网络整体结构活动的结果。联结主义：改良主义的“符号与计算”

第一代认知科学是计算主义立场「无论是符号主义还是亚符号的联结主义」，日益受到人们的强烈质疑，因为不能克服离身心智「disembodied mind」的根本缺陷，被称之为“计算乌云”。

认知研究经历了一次深刻的范式转变，即从基于计算隐喻和功能主义观念的「第一代认知科学」向基于具身心智观念的「第二代认知科学」的转变。

第二代把认知放到实际生活中加以考察，认为认知的本质是一个活的身体在实时环境中的活动, 因此提出了具身认知「embodied cognition」的概念。强调情境性、具身性、动力性成为第二代认知科学的首要特征。受第二代认知科学动力认知观的影响，认知心理学家开始放弃静态表征的传统观点，转向对认知过程的动力学分析。“80年代中期，就在主流认知科学开始转向联结主义时，情境性和具身性这两个概念开始登上学术舞台，90年代初期第三个概念又出现了，那就是动力学……动力取向强调行为的时间维度，寻求使用动力学的概念和工具于认知的分析。

动力取向的认知科学家认为:“大脑本身和身体-脑-环境的三者组合构成了一个复杂的自组织系统，其各部分之间时刻发生的互动突现性地导致了个人适应行为的稳定模式……一个重要的事实是，动力系统理论可以给有机体的复杂适应活动(及其与环境的互动)提供解释, 而不必求助于有关世界的内部表征的概念。

冯•盖尔德（van Gelder）和波特（R.Port）「1995年」出版了一本关于认知科学的动力理论的书：提出认知科学的动力学研究进路被作为认知科学第三种竞争范式的宣言。冯·盖尔德提出动力学假说，「自然的认知系统是某种动力系统，而且动力学眼光理解认知系统是最好的理解」。动力学假说是以数学的动力系统理论为基础描述认知的，用数学的相空间、吸引子、确定性混沌等概念来解释与环境相互作用的人类的内在认知过程。该主义认为应该描述人在特定环境及内在压力下的认知及反应，并且是用微分方程来描述，同时也常用到混沌理论来描述。

动力认知的理论家用数学的非线性动力系统观来看待认知。他们把认知视为嵌入环境中的智能体的实时的适应活动，认知是一个系统事件，认知发展是一个复杂的动力系统中的变化，它是诸多分散的和局部的相互作用的涌现的结果。”从动力认知的观点来看，“认知过程是动力的、非线性的，展现出混沌特征……计算主义没有适当地把握认知的时间特征，仅仅提供了对一串离散的认知状态的描述……”

[认知心理学:困境与转向](http://xbjk.ecnu.edu.cn/CN/html/20100107.htm)
[“认知革命”与“第二代认知科学”刍议-【维普官方网站】-www.cqvip.com-维普网](http://www.cqvip.com/read/read.aspx?id=28974088)

**Comment by tsingyu42** [comment]
ACT-R从最初的HAM「Human Associative Memory」（人类联想记忆）的模型演变而来，1976 年由安德森首次提出，工作重点由记忆转变到学习的 ACT 的构建。1982年出现第一个ACT-R 工具，之后这方面在理论和工具上得到进一步发展，先后发布ACT、ACT-R、ACT-R 2.0、...目前ACT-R 已经发布到 6.0 版本。

**Comment by tsingyu42** [comment]
「人类联想记忆」是在哪一年由谁提出的？

**Comment by tsingyu42** [comment]
直到20世纪90年代中期，在人工智能的第二个寒冬之后，联结主义开始使用深度学习的名头在科学出版物中占据主导地位。

（微信聊天摘录）
