### ISSUE TITLE
「讨论」已经检索的关于计算认知科学的信息

### ISSUE THREAD

**Issue by zapp926** [MaiYunfei2000/IA003CoCoSci#2]
CH2 进阶作业

## 目录 

1. 摘要

2. 背景

3. 目的及问题分析

	3.1 目的
	
	3.2 方法一
	
	3.3 方法二

4. 反思

---

1. 摘要

@todo

2. 背景

> 运用至少两种实践策略，形成对「心理学」或自己感兴趣领域的全局认识，记录探索过程，完成一份信息分析报告。

> 注意：使用的实践策略中须包含「批量下载 1000 篇论文」。

3. 目的及问题分析

	3.1 目的
	
	认知科学主流的研究方向是认知神经科学、计算认知科学和认知心理学。本次想了解计算认知科学的发展现况，建立全局认识。构建一份由42位大牛组成的清单，以大牛为基本单位着手，不断完善作业，最后和其他同学一起完成大的BP。通过时间、空间、变量关系为切入点，具体探索的问题包括：学科诞生的时间、设立之初想要解决的根本问题是什么，因为什么原因而产生的。该学科高级别的概念模型有哪些？其底层体系有哪些？学科 的发展现况，可追踪的期刊、会议有哪些？

	3.2 方法一
	
	3.2.1 检索该领域大牛
	
	使用Google学术，从一个大牛入手。从阳老师博客中了解到MIT的Joshua B. Tenenbaum 在做计算认知科学的研究。Google学术找到其个人档案，发现标签太多，无法定位到其它大牛。「认知科学、人工智能、机器学习、计算神经科学、认知心理学」这些标签中，对认知心理学相对熟悉，先尝试使用「认知心理学」验证Google学术排名的准确性，用「认知心理学」标签检索出前十位大牛。
	
	3.2.2 批量下载大牛文献
	
	起初尝试使用Google学术批量下载论文，即使限定数量—十几篇下载一次，下载次数多了后仍被封掉。就转换到APA的PsycINFO数据库，该数据库收录了心理学和相关学科领域内的200多万篇学术期刊文章、书刊章节、书籍和论文的引文及概要，97% 的收录文献经过同行评审。检索方法是直接以作者姓名为检索词进行检索。PsycINFO数据库的检索能一次批量导出50篇文献。使用PsyINFO数据库批量下载认知心理学中Google学术排名前10的大牛，总计下载了1000篇左右。
	
	3.2.3 交叉验证
	
	下载完毕，批量阅读摘要，没有找到「千篇一律」的感觉。之后进行交叉验证。使用Acemap输入「cognitive psychology」，找到认知心理学的期刊，获取Acemap提供的优秀作者，进行检索。使用wiki, 检索「cognitive psychology」有列出63位有影响力的认知心理学家。使用这份清单，进行验证。结果发现Google学术提供的排名和交叉验证使用的结果有很大出入。交叉验证结果表明使用Google学术的「label」入手，效果不好。
	
	3.3 方法二
	
	3.3.1 检索该领域期刊
	
	检索计算认知科学方向的核心期刊有哪些？从期刊入手，定位大牛。通过检索「Journal AND computational cognitive science」，找到一本专门的期刊《computational cognitive science》，由Springer 在2015年创办的，但到了2016年这个期刊就停刊了，两卷只收录了10篇文献。其它期刊还在继续探索。。。。。@todo
	
	3.3.2 检索该领域实验室
	
	通过Google、google researchgate、Quora等信息源，检索到几个专门研究该领域的实验室，可以用来追踪进展。[Charles Kemp](http://www.charleskemp.com/)、[computation and cognition lab](http://gureckislab.org/index.php)、[computational Cognitive Science](http://cocosci.princeton.edu/index.php)、[Geoffrey E. Hinton](http://www.cs.toronto.edu/~hinton/)、[MIT Computationan Cognitive Science Group](http://cocosci.mit.edu)、[Tom Mitchell homepage](https://www.cs.cmu.edu/~tom/)、[Matthew M Botvinick](https://www.researchgate.net/profile/Matthew_Botvinick)、[UNSW Computational Cognitive Science](https://compcogscisydney.org/)、[Indiana_Computational Cognitive Neuroscience Laboratory](http://www.indiana.edu/~cortex/index.html).
	
	3.3 方法三
	
	使用PsycINFO检索「Cognitive Science」下载了1000篇论文，待分割研究，找到「计算认知科学」部分。

4. 反思

	* 检索过程中发现「computational cognitive science」这个检索词检索效果差。还需要尝试其它检索词，如「Computational cognition」、「computational psychology」。
	
	* 这样检索很难批量下载到1000篇文献，并且耗时费力。接下来的思路，直接从「Cognitive Science」上位词入手，批量下载1000篇文献，再利用Zotero高级检索功能筛选。之所以没有一开始就使用「Cognitive Science」检索，在于其涉及的领域太多，容易区分不开。

	* zotero踩过的坑。
	
		* 导入文件放入新的集合中取消勾选的话，会直接放入到我的文库中。
		
		* 使用zotero Scholar Citations 如果出现JavaScript Application 警告的话，那就是被Google学术封锁了，换IP也是不行的。按照作者在Github—README.md 的说法，唯一的办法就是等一段时间，直到解锁。

### ChangeLog

* 181223 添加部分细节内容。

* 181222 刘旭写下部分内容，定下大体框架。

**Comment by tsingyu42** [comment]
`4.反思`：

是的，所以需要获取学科的二级话语体系，比如卡包里所说，人工智能下有「深度学习」、「神经网络」等，要靠后者检索而不是前者。
