### ISSUE TITLE
报告区|项目进展情况

### ISSUE THREAD

**Issue by tsingyu42** [MaiYunfei2000/IA003CoCoSci#6]
此issue用于反馈任务进展。

---

## todolist_流程ver

**1 收集信息 输出文件**

* 时间：学科发展脉络
  - [ ] 每个学派的发展脉络
    - [ ] Connectionist Models of Cognition
    - [ ] Bayesian Models of Cognition
    - [ ] Dynamical Systems Approaches to Cognition
    - [ ] Declarative/Logic-Based Cognitive Modeling
    - [ ] Constraints in Cognitive Architectures
  - [ ] 提炼、概括，汇总至一个时间轴（是汇总一条线还是分四个学派，待定）
* 空间：大牛和重要机构的清单及分布情况
  * 大牛
    - [x] 大牛清单
    - [ ] 挑选出主要大牛
      - [ ] 制作人名卡
      - [ ] 收集学者关系
      - [ ] 收集学者主要著作的社会引用情况
  * 机构
     - [x] 机构清单
     - [ ] 机构分布状况可视化
  * 合并
    - [ ] 学者机构分布状况可视化
* 变量关系：研究主题（主要的话语及其体系）
  - [ ] 每个学派的核心话语
    - [ ] Connectionist Models of Cognition
    - [ ] Bayesian Models of Cognition
    - [ ] Dynamical Systems Approaches to Cognition
    - [ ] Declarative/Logic-Based Cognitive Modeling
    - [ ] Constraints in Cognitive Architectures

**2 将文件合并成项目**

- [ ] 制作PPT框架
- [ ] 把各个小组块丢进PPT
- [ ] 添加有趣度，润饰PPT
- [ ] 完善PPT，练习演讲

## todolist_成品大纲ver

* 引入（小故事）
* 正文
  * 时间（按四个流派或是合一？待定）
  * 空间
    * 大牛、机构的分布
    * 大牛与大牛的关系
  * 变量（按四个流派展开主要话语体系）
  * 社会关注情况
* 项目最终目的
* 成员介绍&灌水

---

此外，收集到了些杂货也可补充在这里。

---

当前成果：[谷歌表格-学者和机构清单](https://docs.google.com/spreadsheets/d/16KGHR6A6p53P2mI5wxl-pNAUHyIcl1hbIAJpkoGcNHg/edit)

这个表格是很重要很关键的东西之一。

**Comment by zapp926** [comment]
190109w5d4

### List of cognitive neuroscientists

* 在wiki上找到认知神经科学家的名单，在里面应该能筛选出来「计算认知科学的大牛」。『[具体地址](https://en.wikipedia.org/wiki/List_of_cognitive_neuroscientists)』

### institution

从下面几个机构看，美国和加拿大是研究的重镇。还需验证。其它机构暂时检索不到了。根据以往的知识，英国的伦敦大学也是很厉害的。

* [Charles Kemp](http://www.charleskemp.com/)
* [computation and cognition lab](http://gureckislab.org/index.php)
* [computational Cognitive Science](http://cocosci.princeton.edu/index.php)
* [Geoffrey E. Hinton](http://www.cs.toronto.edu/~hinton/)
* [MIT Computationan Cognitive Science Group](http://cocosci.mit.edu)
* [Tom Mitchell homepage](https://www.cs.cmu.edu/~tom/)
* [Matthew M Botvinick](https://www.researchgate.net/profile/Matthew_Botvinick)
* [UNSW Computational Cognitive Science](https://compcogscisydney.org/)
* [Indiana_Computational Cognitive Neuroscience Laboratory](http://www.indiana.edu/~cortex/index.html)

### Paper

* Computational Cognitive Science. 里面的几篇文献看了，没有发现太多有用的信息，好多内容很难理解。下面是相对有用的一句话。

    * 计算智能和认知科学越来越多地反映了构建智能应用程序和实体的应用目标与理解现有智能实体和功能的纯粹目标之间的对比，我们似乎缺乏它们之间的桥梁。计算认知科学旨在提供这种桥梁。

### Others

* 查找到[认知科学学会](http://www.cognitivesciencesociety.org/
)。
    * 里面检索到一个「[Computational Modeling Prizes](http://www.cognitivesciencesociety.org/conference/cogsci-2019/awards/)」这个奖项，应该是专门针对计算认知的，可以顺着这条路线检索出来历年获得该奖项的研究者。
    * 还有这个[David E. Rumelhart奖](http://www.cognitivesciencesociety.org/rumelhartprize/)，都和咱们研究的问题有关。


* 通过维基百科检索
[Category:American psychology awards](https://en.wikipedia.org/wiki/Category:American_psychology_awards). 找到
「[Troland Research Awards](https://en.wikipedia.org/wiki/Troland_Research_Awards)」,和咱们的研究主题有一定关系。

* [cognitive science](https://www.sciencedirect.com/journal/cognitive-science)这本期刊里的文章有待挖掘。

* 神经信息处理系统大会（NIPS），这个大会是AI和计算神经科学的会，也可以挖一下。

* [「计算认知神经科学」](https://grey.colorado.edu/CompCogNeuro/index.php/CCNBook/Intro)书一本。

* 检索到一个高级模型「[ACT-R](http://act-r.psy.cmu.edu/)」，由卡耐基梅隆大学的心理学系提出的。

需要做的工作还很多，我刚好这两周同时有几件事要做，都很紧急，所以时间比较少。具体怎么办，我觉得咱们需要Zoom尽快讨论一下。确定一个方向，先建立出来一个最小全局认识再说，不能再同时单兵作战，尽量协作起来。

看看大家的意思。

**Comment by zapp926** [comment]
补充[「认知建模资源」](https://web.archive.org/web/20081223021829/http://cognitivesciencesociety.org:80/resource_cognitive_modelling.html)

**Comment by tsingyu42** [comment]
[Bayesian cognitive science - Wikipedia](https://en.wikipedia.org/wiki/Bayesian_cognitive_science)
