### ISSUE TITLE
cognition science task

### ISSUE THREAD

**Issue by zapp926** [MaiYunfei2000/IA003CoCoSci#7]
队长写的那个流程清单很详细、具体，可以按照那个整理。可能出现的问题是，限入细节中，如果遇到什么坑就先跳过。总的认识可以按照这个框架来填入相应信息。

#### task1

* 任务：把咱们三个人已经整理好的文献汇总，按照这四个象限，对文献进行梳理。
* 目的：得到各个象限的一个清单列表，和相应的总结。
![](https://ws2.sinaimg.cn/large/006tNc79ly1fyxv3ch8t6j30e30avweg.jpg)

#### task2
* 任务：按照时间、空间、变量关系对资料进行拆解梳理。
* 目的：
    - 得到学科发展的时间脉络「诞生时间、转折点、重大事件 etc」
    - 得到学科的空间分布，如学术科研重镇
    - 找到「认知科学」作为自变量和因变量，相关的影响因素
    - 汇总成一个最小全局认识。如该学科诞生的目的是为了解决什么问题，其核心理论是什么 etc.

#### task3

* 任务：按照这个2 x 2 的表格找相应的知识点。
* 目的：在单一维度或者交叉的象限中得到罗列几个知识点，重点是有趣的反常识
![](https://ws3.sinaimg.cn/large/006tNc79ly1fyxvi5nl9ej30il09ywec.jpg)

#### ChangeLog

* 190107 ZAPP 创建

**Comment by tsingyu42** [comment]
Good👍🏻不过得记得task1的那个框架是针对学者的。（先提一下避免之后走错路）

**Comment by zapp926** [comment]
@MaiYunfei2000 

按照这个说法是可以顺着这条线走的，我会适当调整的

![](https://ws1.sinaimg.cn/large/006tNc79gy1fyyf7xby2uj30np0ipmxv.jpg)
