### ISSUE TITLE
公告|不知能否救场的思路

### ISSUE THREAD

**Issue by tsingyu42** [MaiYunfei2000/IA003CoCoSci#8]
# 切割项目尺寸

## 前言

我们都面临着严重缺乏时间的窘境（例如，我这两周在期末考，下周三(6wd3)才考完最后一科；刘旭同学最近也要同时处理几份紧急事务），那么可以果断地判定，按照原本的思路来完成项目是不可能的了。综合他人的建议和自己的想法，我认为得切割选题。

> 选题1 找到领域榜样  
> 
> 请分析感兴趣的 1-2 领域，广泛了解领域内的大牛，分析其中 1-2 位大牛的知识结构以及对自己接下来行动的启发点。可为学术牛人、商业牛人等。

也就是说，把我们的项目收束成【1份牛人清单+1份CH2进阶作业②】，也就是【寻找一批领域内的牛人+从中选出一个大牛+运用CH2所教的学者信息分析框架形成此大牛的最小全局认识】。那么这样一来思路就小很多了，而且因为我进阶②的探索度还OK，所以比较清楚接下来该怎么做，以及具体有哪些步骤是我可以胜任的，哪些是我相对薄弱而你们相对擅长的。这样下来就是三人合力完成一份进阶作业，工作量明显降下来，少了许多费时费力的发散摸索。并且任务颗粒度变小了，执行起来清晰很多。

以下是主要内容。

## bp-idea-v2.0

PS：`*(数字)xxx*`是本次项目可分配到个人的最小任务的唯一编码。此节末尾有整理出的一份表格，参见**附录一 最小任务清单**。

**STEP0**：5wd5 21:42第一次会议

主题一：明确接下来可全身心投入的时间  
主题二：任务分工

**STEP1**：生成一份牛人清单(*1001*)。

1. 发散式，沿着各种痕迹和线索，在网络的各个角落找出一个个大牛。收集他们的基本信息（姓名，所在机构，GoogleScholarProfile上的tags，h指数，被引总数，单篇最高被引数，个人主页或所在机构主页）放在[我已建好的GoogleDocs文档](https://docs.google.com/spreadsheets/d/16KGHR6A6p53P2mI5wxl-pNAUHyIcl1hbIAJpkoGcNHg/edit#gid=0)里。
2. 复制到本地，使用Excel的排序功能将其按h指数排列。
3. 将排序好的文档放回到网上方便共享。
4. 参考IAToolKit制作成GitHub上的信息工具箱。
5. 这个可以一人完成，其它人补充或是进行交叉验证(*1002*)。

**STEP2**：选定一个拿来报告的大牛。

* 这是**第二次zoom会议**的核心议题。
* 依据些什么来选定呢？
    * 信息充足的，例如连Acemap上都有ta的信息。
    * 认知计算/神经兼通的。

**STEP3**：使用课程所教的信息分析框架分析这个大牛。

学术信息分析框架的四象限：学术论文、知识图谱、专业图书、社会引用。

* **基本信息**：生平，身份，踏足领域，主要成就。维基；Google找个人主页。→**输出1张人名卡**(*3101*)。
* **学术论文**：
    * 保存该学者的全部论文，放至zotero共享目录。(*3201*)
    * 找出该学者的成名作，贴上标签`成名作`。(*3202*)
    * 找出该学者的里程碑著作，贴上标签`里程碑`。(*3203*)
    * 找出学者的最新三篇论文，贴上标签`最新三篇`。(*3204*)
    * 找出学者引用最高的三篇论文，贴上标签`最高被引`。(*3205*)
    * (*难度大)找出学者最早被引的三篇论文，贴上标签`最早被引`。(*3206*)
    * 把上述论文列成一个清单。(*3207*)
    * **第三次zoom会议**：每人认领清单中的论文。
    * 结构阅读法阅读上述论文→**每篇论文输出1~3张术语卡**。(*序列 预留3210~3250段*)
    * Zotero创建时间轴，定下时间颗粒度后，一段时期一段时期地概括学者的研究主题，**输出一张表格**（参见**附录二**）。(*3251*)
* **知识图谱**：
    * 大牛的主要合作伙伴(*3301*)
        * 谷歌学术(esp. co-authors)
        * 百度学术
        * Bing学术
        * Acemap
        * Neurotree
        * 人肉挖掘文献引文
    * 大牛的主要引用关系(*3302*)
        * Citespace是不存在的了orz，我们只能找现成的。所以如果Acemap有存这个学者的数据，那自然是最好的。
* **专业图书**：（视具体情况，有可能舍去此维度）
    * 找出大牛的专业图书，存入zotero(*3303*)
    * 选择一本作为阅读对象（阳老师推荐的那本handbook或许可以）
    * 抽样阅读一本大牛的学科代表作→**每章节输出一张术语卡**（注意，略读就可以了，要的只是术语及其概念）。（若是厚书，可以拆分章节，各自认领）(*序列 预留3310~3340段*)
* **社会引用**：
    * 使用AltMetric了解大众对计算认知科学topic的看法→**输出1张任意卡**。(*3401*)

**STEP4**：FINAL ROUND (*4001*)

1. 汇总、整理信息（按照时空变量维度）
2. 拼接卡片成文
3. 输出PPT
4. 预演，迭代

## 后记

尴尬的是，接下来一波比这周重得多的考试即将到来，所以我最早只能下周三下午之后开始工作。

所以需要大家确认一下自己接下来**可以全身心投入开智项目的时间**。

明确了这些之后，我基于积蓄已久的爆肝之力，即便只有三天时间，也有很高的成功率做出BP的demo。

## 可参考的资料

* 作业
    * [王涤宇同学](https://m.openmindclub.com/stu/IA003/work/bf382699-be4f-4d03-94f5-ea12bb5fde9d)
    * [王杨同学](https://m.openmindclub.com/stu/IA003/work/bf382699-be4f-4d03-94f5-ea12bb5fde9d)
    * [张弘同学](https://m.openmindclub.com/stu/IA003/work/bf382699-be4f-4d03-94f5-ea12bb5fde9d)
    * [淡暖同学](https://m.openmindclub.com/stu/IA003/work/bf382699-be4f-4d03-94f5-ea12bb5fde9d)
    * [beibei同学](https://m.openmindclub.com/stu/IA003/work/bf382699-be4f-4d03-94f5-ea12bb5fde9d)
    * [胡丽同学](https://m.openmindclub.com/stu/IA003/work/bf382699-be4f-4d03-94f5-ea12bb5fde9d)
    * [舟舟同学](https://m.openmindclub.com/stu/IA003/work/bf382699-be4f-4d03-94f5-ea12bb5fde9d)
* 卡片
    * [构建优雅的知识创造系统 - 阳志平的网志](https://www.yangzhiping.com/psy/yang-KnowledgeSystem.html)
    * [跨年答疑（3）：卡片十二问 - 阳志平的网志](https://www.yangzhiping.com/psy/happy-new-year-faq3.html)
    * [跨年答疑（1）：学习十二问 - 阳志平的网志](https://www.yangzhiping.com/psy/happy-new-year-faq1.html)
    * [读书十二问 - 阳志平的网志](https://www.yangzhiping.com/psy/live002.yangtalk.html)

持续更新。

### 附录一 最小任务清单

放在[这个谷歌文档](https://docs.google.com/spreadsheets/d/16KGHR6A6p53P2mI5wxl-pNAUHyIcl1hbIAJpkoGcNHg/edit#gid=1572507358)里。

### 附录二 学者关注话题的动向

模板表格。

| 时间段 | xxxx-xxxx | xxxx-xxxx | xxxx~xxxx |
| -------- | -------- |------ | -------- |
| 主题 | 关键词| 关键词| 关键词 |

## changelog

190110 1250 麦云飞建立文档。

**Comment by tsingyu42** [comment]
补充思路：可以从计算机科学奖项（如图灵奖）的获奖者中找心理学家。

**Comment by ailian8025** [comment]
your gay plan is amazing! but what's the process and result?

**Comment by tsingyu42** [comment]
> your gay plan is amazing! but what's the process and result?

@ailian8025 Got stuck due to the repo-owner's insufficient IQ and knowledge as well as huge life unfortune. 

MYF is a Psychology student who yearn to learn much math (esp. probability theory) and CS esp. machine learning but his school offers nothing and his university doesn't offer minors in math or CS or physics, and he's just currently struggling with MITx 6.86x while bearing tons of boring and trivial human resource management courseload as usual LOL🤣

He has never give up!

**Comment by tsingyu42** [comment]
技能曲线太抖了。

```python
while True:
    try:
        看文献
    except 看不懂
        滚去学!
```

这个循环滚了好几次了。这几年一边应对各种崩溃事情一边自学Python、线代、概率论、统计afawawieofhashfioaheo挺GG的，后悔没在大三前转专业去计算机或者数学。

**Comment by tsingyu42** [comment]
下个月又会开始尝试不自量力地去啃相应文献了，明年应该会开始填坑了吧23333333

**Comment by tsingyu42** [comment]
@ailian8025 不过当时产出的汇报PPT你需要不（虽然现在看来信息量不大了。。。），需要的话加微信13543428624附上备注

**Comment by tsingyu42** [comment]
这个仓库的定位就是改装成awesome，但是因为各种历史现实原因咕咕咕

**Comment by ailian8025** [comment]
> 

good luck!
