### ISSUE TITLE
结业bp分享会

### ISSUE THREAD

**Issue by xdpwjj** [MaiYunfei2000/IA003CoCoSci#9]
# 结业bp分享会

### 胡丽

> 没有经历bp的人生是不完整的
因初心而坚持，因队友而不放弃

- 协作
- 收获
    - 过度收集信息|善用课程分析框架，学术or商业？--设置项目边界，设置ddl
    - 协作工具|GitHub转到Notion--越简单越好，减少学习成本
    - 项目进度等争议|先demo还是先收集信息？--真诚沟通，明确分歧，用行动说话
    - 内容太多|组员打磨、利用课程框架--大幅删减、反复演练
    
### 雅琳

- 遇到问题
    - 没有方向|尽早确定，节约时间
    - 输出太少
    - 内容太多|卡包：有趣度，删减内容可以最后清单呈现
    - 时间
    
- 大作业收获
    - 熟悉课程的策略
    - 集体智慧
    - 路演考验综合能力
    
- 建议
    - 做大作业|踩坑填坑
    - 输出
    - 约束|项目方向、内容
    - 项目难推进|卡片输出作为最小行动

## 2.已有项目疑问

【Q1】路演时间
【A1】15min，包括项目演示和回答问题

【Q2】[婉嫣同学](https://m.openmindclub.com/stu/IA003/discussion/51ade664-efc5-46f6-9ef7-8837c73a2053)

【A2】

【阳】

- 结构要有所约束 
- 搜索 GitHub 已有仓库数据 
- 可以去城市规划局 
- 寻找反常识的信息点

【李仁冲】

- 参考陈虎平老师那个视频
陈虎平. (2017a, 九月 13). 陈虎平：市井雄心——城市演化与人生设计（上） | 开智大会主题演讲 [mp]. 取读于 2018年12月26日, 从 https://mp.weixin.qq.com/s/glL-toD_kTHX1WDG4_eZqQ
陈虎平. (2017b, 九月 14). 陈虎平：市井雄心——城市演化与人生设计（下）| 开智大会主题演讲 [mp]. 取读于 2018年12月26日, 从 https://mp.weixin.qq.com/s/rKhzhSLgniSkx_nFcVOGRQ

【Q3】搜索关键词
【A3】针对提问阳老师给出了更多相关关键词，比如网络科学，更多的检索词是**系统类科学，数学图论，物理统计力学；社会学的社会网络分析……**

【A4】针对若干个项目，阳老师统一回复的策略：

- 新信息，面向未来，或者反常识……
- 项目定义不要太大，否则陷入信息汪洋。约束边界。确定不研究的内容，精确入手角度。
- 交叉学科，跨学科形成全局认识，需要从专家从综述等获得一些前置信息。
- 知道查找一些手册，了解跨学科研究学者形成的一些学科共识。比如某个学科的通识读物，或者教材导论，或者综述或者学科wiki等等

【Q5】 我是战略小组成员，我们尝试建立战略的最小全局，输出时间，空间和变量三张大表，作为第一部分的学术展示。第二部分准备展示战略及案例，但是在案例过程中无从下手，尝试着做，觉得对战略吃不透，套起案例很吃力。但是时间又有限，该如何有效进入后面的案例中。阳老师有没有好的建议
【A5】某个学科的通识读物，或者教材导论，或者综述或者学科wiki等等。约束边界，约束边界。

【Q6】这是计算认知小组[实践策略](https://github.com/MaiYunfei2000/IA003ComputationalCognitiveScience/blob/master/readme.md)，请问阳老师有什么补充？
【A6】
 这些基本就是未来涉及的参考文献。计算认知科学，核心是这几本，这块就几乎没中文参考了：
 
 - [The Cambridge Handbook of Computational Psychology (豆瓣)](https://book.douban.com/subject/3219419/)  这本是最重要的。大师们的合集。
- [Computational Neuroscience and Cognitive Modelling (豆瓣)](https://book.douban.com/subject/25816519/)  这本书更接地气。直接教你如何用 Python 代码来对人类心智建模。也是一本近些年的计算认知科学与计算神经科学入门好书。
- 还有一本非常关键的，我得找找。

关于计算认知科学主要有4个流派，每个流派都有代表人物。（具体内容见书）

【Q7】要做的事太多，可用的时间却不够？
【A7】算法 we live by
That’s the premise of Algorithms to Live By, a book by Brian Christian and Tom Griffiths.
这是布赖恩•克里斯蒂安(Brian Christian)和汤姆•格里菲思(Tom Griffiths)合著的新书《赖以生存的算法》(Algorithms to Live By)中提出的主张。

【A8】阳老师补充核心脉络

- 信息是无穷的，要抓住变化比较少的
- 学术渊源脉络
- 研究机构 流域作为分界
- 抓主要矛盾
- 领域中最简洁的分类框架, 任何领域都可以，比如学校分为超一流...
- 约束边界，挖掘别人未知的信息，项目要能给大家一些新的指导

## 3.小组讨论

没有组队小伙伴互相勾搭

changelog
190111 0016 王婧婧完成结业bp分享会内容整理

**Comment by zapp926** [comment]
大致听了一下，阳老师提到的流派：
* 贝叶斯流派-约书亚·特南鲍姆「贝叶斯网路」
* 深度学习-韩丁老师「深度学习、反向传播」+ 杰弗里·辛顿
* ACT-R-安德森「认知架构、自适应学习、计算机辅助教学系统」
* 另一个需要再查一下
